# -*- coding: utf-8 -*-

"""Hanwha 0907.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j96jid9FpfRWer8JJvpjE1I3T5Zxcrvw
"""

# Import
from datetime import datetime
from pydantic import BaseModel, PositiveInt
from typing import Annotated, Literal
from annotated_types import Gt
from pydantic import BaseModel

# 클래스 선언부
class User(BaseModel):
  id: int
  name: str = 'John Doe'
  signup_ts: datetime | None
  tastes: dict[str, PositiveInt]

# 데이터
external_data = {
  'id': 123,
  'signup_ts': '2019-06-01 12:22',
  'tastes': {
      'wine': 9,
      b'cheese': 7,
      'cabbage': '1',
  },
}

# User 오브젝트 생성
user = User(**external_data)

print(user.id)
print(user.signup_ts)
print(user.tastes)

print(user.model_dump())

from pydantic import BaseModel, ValidationError

external_data2 = {
    'id': 'not an int',
    'tastes': {}
}

try:
    User(**external_data2)

except ValidationError as e:
    print(e.errors())

class Fruit(BaseModel):
  name: str
  color: Literal['red', 'green']
  weight: Annotated[float, Gt(0)]
  bazam: dict[str, list[tuple[int, bool, float]]]

print(
  Fruit(
      name='Apple',
      color='red',
      weight=4.2,
      bazam={'foobar': [(1, True, 0.1)]},
  )
)

class meeting(BaseModel):
  when: datetime
  where: bytes
  why: str = 'No idea'

m = meeting(when='2020-01-01T12:00', where='home')

print(m.model_dump(exclude_unset=True))
print(m.model_dump(exclude={'where'}, mode='json'))
print(m.model_dump_json(exclude_defaults=True))